import "@/app/globals.css";

import Provider from "@/components/Hoc/Provider";
import { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Toaster } from "sonner";
import { Roboto } from "next/font/google";

const font = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Realtime Solutions",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  // 1. Lấy locale từ params
  const { locale } = await params;

  // 2. Lấy danh sách từ điển (messages) từ Server
  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${font.className} antialiased`}>
        {/* 3. QUAN TRỌNG: Phải bao bọc nội dung bằng Provider này 
             thì các file "use client" bên trong mới dùng được hàm t() */}
        <NextIntlClientProvider messages={messages}>
          <Provider>
            {children}
            <Toaster position="top-center" richColors />
          </Provider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
